// <autogenerated />
namespace Namespace_32_Converter
{
	partial class MainForm
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.textToProcessLabel = new System.Windows.Forms.Label();
			this.textToProcessTextBox = new System.Windows.Forms.TextBox();
			this.namespaceButton = new System.Windows.Forms.Button();
			this.displayNameButton = new System.Windows.Forms.Button();
			this.copyToClipboardCheckBox = new System.Windows.Forms.CheckBox();
			this.SuspendLayout();
			// 
			// textToProcessLabel
			// 
			this.textToProcessLabel.Location = new System.Drawing.Point(8, 8);
			this.textToProcessLabel.Name = "textToProcessLabel";
			this.textToProcessLabel.Size = new System.Drawing.Size(150, 23);
			this.textToProcessLabel.TabIndex = 0;
			this.textToProcessLabel.Text = "&Text to process:";
			// 
			// textToProcessTextBox
			// 
			this.textToProcessTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
									| System.Windows.Forms.AnchorStyles.Right)));
			this.textToProcessTextBox.Location = new System.Drawing.Point(6, 32);
			this.textToProcessTextBox.Name = "textToProcessTextBox";
			this.textToProcessTextBox.Size = new System.Drawing.Size(414, 26);
			this.textToProcessTextBox.TabIndex = 1;
			// 
			// namespaceButton
			// 
			this.namespaceButton.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
									| System.Windows.Forms.AnchorStyles.Left)));
			this.namespaceButton.Location = new System.Drawing.Point(38, 60);
			this.namespaceButton.Name = "namespaceButton";
			this.namespaceButton.Size = new System.Drawing.Size(170, 32);
			this.namespaceButton.TabIndex = 2;
			this.namespaceButton.Text = "&Namespace";
			this.namespaceButton.UseVisualStyleBackColor = true;
			this.namespaceButton.Click += new System.EventHandler(this.OnNamespaceButtonClick);
			// 
			// displayNameButton
			// 
			this.displayNameButton.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
									| System.Windows.Forms.AnchorStyles.Right)));
			this.displayNameButton.Location = new System.Drawing.Point(218, 60);
			this.displayNameButton.Name = "displayNameButton";
			this.displayNameButton.Size = new System.Drawing.Size(170, 32);
			this.displayNameButton.TabIndex = 3;
			this.displayNameButton.Text = "&Display name";
			this.displayNameButton.UseVisualStyleBackColor = true;
			this.displayNameButton.Click += new System.EventHandler(this.OnDisplayNameButtonClick);
			// 
			// copyToClipboardCheckBox
			// 
			this.copyToClipboardCheckBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
									| System.Windows.Forms.AnchorStyles.Right)));
			this.copyToClipboardCheckBox.Checked = true;
			this.copyToClipboardCheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
			this.copyToClipboardCheckBox.Location = new System.Drawing.Point(252, 8);
			this.copyToClipboardCheckBox.Name = "copyToClipboardCheckBox";
			this.copyToClipboardCheckBox.Size = new System.Drawing.Size(168, 24);
			this.copyToClipboardCheckBox.TabIndex = 4;
			this.copyToClipboardCheckBox.Text = "&Copy to clipboard";
			this.copyToClipboardCheckBox.UseVisualStyleBackColor = true;
			// 
			// MainForm
			// 
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
			this.ClientSize = new System.Drawing.Size(427, 98);
			this.Controls.Add(this.copyToClipboardCheckBox);
			this.Controls.Add(this.displayNameButton);
			this.Controls.Add(this.namespaceButton);
			this.Controls.Add(this.textToProcessTextBox);
			this.Controls.Add(this.textToProcessLabel);
			this.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.MaximizeBox = false;
			this.MaximumSize = new System.Drawing.Size(4000, 132);
			this.MinimumSize = new System.Drawing.Size(435, 132);
			this.Name = "MainForm";
			this.Text = "Namespace Converter";
			this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.OnMainFormFormClosing);
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		private System.Windows.Forms.CheckBox copyToClipboardCheckBox;
		private System.Windows.Forms.TextBox textToProcessTextBox;
		private System.Windows.Forms.Button displayNameButton;
		private System.Windows.Forms.Button namespaceButton;
		private System.Windows.Forms.Label textToProcessLabel;
	}
}
